#!/bin/sh
Usage(){
	echo "Usage: $1 <filename>"
	exit 1
}

if [ $# -ne 1 ]; then
   Usage $#
fi


if [ -d $1 ]; then
   tar czvf $1.tar.bz2 $1

else 
   echo "No such a directory"
   exit 1   
fi

exit 0
