#!/bin/sh

for i in `ls`; do
    case "$i" in 
    	*.gz) gunzip $i
	    ARG="$i"
	    NAME="${ARG%.gz}"
	    NAME_bz2="$NAME.bz2"

	    echo "ZIP形式"
    	    du -b $NAME       #バイト単位で容量表示
	    echo "*******************************"

	    bzip2 $NAME
	    echo "bz2形式"
    	    du -b $NAME_bz2
	    ;; 
    esac
done